name: Linux Clang
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ubuntu_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        clang-version: [9, 10, 11]
        exclude:
          # excludes clang-11 on Ubuntu 18.04 because it doesn't exist in the
          #standard repositories.
        - os: ubuntu-18.04
          clang-version: 11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev \
                                  libxrandr-dev \
                                  libxinerama-dev \
                                  libxcursor-dev \
                                  libxi-dev \
                                  clang-${{ matrix.clang-version }}
            
      - name: Configure CMake
        run: |
          cmake -HEditor \
                -B${{ github.workspace }}/build \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -G"Unix Makefiles"
        env:
          CC: clang-${{ matrix.clang-version }}
          CXX: clang-${{ matrix.clang-version }}
          CXXFLAGS: -lstdc++
          
      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build \
                --config ${{ env.BUILD_TYPE }} \
                -- -j2
