name: OSX
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  mac_os_build:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode-version: ['12.0', latest-stable]
        #From 12.1 to 12.4 (inclusive), all XCode versions use the same
        #compiler version.
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
            
      - name: Configure CMake
        run: |
          cmake -HEditor \
                -B${{ github.workspace }}/build \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -G"Unix Makefiles"
          
      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build \
                --config ${{ env.BUILD_TYPE }} \
                -- -j2
